packages: 
  - htop
  - samba
  - vim
  - android-tools-adb

update : sudo apt update && sudo apt upgrade -y
install : sudo apt install 

git_url: 'https://github.com/MVrauwdeunt/Ansible'
vault_password_file: vault.yml

git_repos:
  - { repo: 'Ansible', url: 'https://github.com/MVrauwdeunt/Ansible' }
  - { repo: 'kiauh', url: 'https://github.com/dw-0/kiauh'}
user: zanbee 
