packages: 
  - htop
  - samba
  - vim
  - python3
  - python3-pip
  - python3-dev
  - python3-setuptools
  - python3-venv
  - libyaml-dev
  - build-essential
  - libffi-dev
  - libssl-dev
  - android-tools-adb

update : sudo apt update && sudo apt upgrade -y
install : sudo apt install 

git_url: 'https://github.com/MVrauwdeunt/Ansible'
vault_password_file: .vault.key

git_repos:
  - { repo: 'Ansible', url: 'https://github.com/MVrauwdeunt/Ansible' }
  - { repo: 'kiauh', url: 'https://github.com/dw-0/kiauh'}
  #- { repo: 'klipper', url: 'https://github.com/Klipper3d/klipper'}
  #- { repo: 'moonraker', url: 'https://github.com/Arksine/moonraker.git'}
  #- { repo: 'klipperscreen', url: 'https://github.com/KlipperScreen/KlipperScreen.git'}

user: zanbee 
