- include_vars: "vars/vars.yml"
  tags: always

- include_vars: "vars/vault.yml"
  tags: always

- hosts: localhost
  connection: local
  become: true
  #vars_files: 
  #  - vars/vars.yml
  #  - vars/vault.yml

  pre_tasks:
    - name: update repositories
      apt:
        update_cache:: yes
      changed_when: False
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- hosts: mediaplayer
  tags: mediaplayer
  become: true
  roles:
    - base
    - server
    - mediaplayer
