
# - hosts: all
#   become: true

#   pre_tasks:
#     - name: update repositories
#       apt:
#         update_cache: yes
#       changed_when: False
#       when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
# - hosts: mediaplayer
#   tags: mediaplayer
#   become: true
#   pre_tasks:
#     - include_vars:
#         dir: "vars/{{ ansible_host | lower }}"
#       tags: always
#   roles:
#     - base
#     - server
#     - mediaplayer

# - hosts: workstation
#   tags: workstation
#   become: true
#   pre_tasks:
#     - name: Debug host name
#       debug:
#         msg: "This is the curent hostname {{ ansible_host }} and in lowers {{ ansible_host | lower }}"
    # - include_vars:
    #     dir: "vars/{{ ansible_host }}"
    #   tags: always
#   roles:
#     - base
#     - workstation

- hosts: DNS
  tags: server
  become: true
  pre_tasks:
    - include_vars:
        dir: "vars/{{ ansible_hostname |lower }}"
      tags: always

  roles:
    - base
    - artis3n.tailscale
      vars:
        # Example pulling the API key from the env vars on the host running Ansible
        tailscale_authkey: "{{ TAILSCALE_KEY }}"
        tailscale_args: "--ssh"
#     - server


#- hosts: satalites
#  tags: satalites
#  become: true
#  pre_tasks:
#    - include_vars:
#        dir: "vars/{{ ansible_host }}"
#      tags: always
#  roles:
    #- base
#    - geerlingguy.docker
    
