- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache:: yes
      changed_when: False
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- hosts: mediaplayer
  tags: mediaplayer
  become: true
  roles:
    - server
    - mediaplayer
