- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"
    #- name: update repositories
    #  apt:
    #    update_cache:: yes
    #  changed_when: False

- hosts: mediaplayer
  tags: mediaplayer
  become: true
  roles:
    - mediaplayer
