- hosts: all
  become: true

  pre_tasks:
    # - name: update repositories
    #   apt:
    #     update_cache: yes
    #   changed_when: False
    #   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Debug host name
      debug:
        msg: "This is the curent hostname {{ ansible_nodename }} and in lowers {{ ansible_nodename | lower }}"
    # - include_vars:
    #     dir: "vars/{{ ansible_host }}"
    #   tags: always