- name: Ensure mountpoints exists.
  file: 
    dest: "{{ item.mount }}"
    state: directory
  loop: "{{ disks }}"

- name: Mount Harddisks.
  mount:
    path: "{{ item.mount }}" 
    src: "{{ item.disk }}"
    opts: "{{ item.options }}"
    dump: "0"
    passno: "0"
    fstype: "{{ item.fs }}"
    state: present
  loop: "{{ disks }}"