---

- name: Ensure required entries are made to exports file.
  lineinfile:
    path: /etc/exports
    state: present
    line: "{{ item.share }}  *(rw,fsid={{ item.fsid }},no_root_squash,no_subtree_check,insecure)"
  loop: "{{ nfs_shares }}"
  # with_items:
  #   - '/export/volumes  *(rw,no_root_squash,no_subtree_check,insecure)' 