---

- name: generate Samba config file from template
  # become: yes
  template:
    src: templates/smb.conf.j2
    dest: "/etc/samba/smb.conf"
    owner: "root"
    group: "root"
    mode: 0644

- name: restart smbd
  service:
    name: smbd
    state: restarted
  become: true