---

- name: Ensure Github directory exists.
  file: 
    dest: "/home/{{ user }}/Github"
    mode: 0700 
    owner: "{{ user }}" 
    state: directory

- name: Clone a github repository
  git:
    repo: "{{ item }}"
    dest: "/home/{{ user }}/Github/{{ repo }}"
    clone: yes
    update: yes
  with_items: "{{ git_repos }}"