- name: Install a private SSH key
  vars:
    source_key: files/id_ed25519
    dest_key: /home/{{ uzer }}/.ssh/id_ed25519
  tasks:
  - name: Ensure .ssh directory exists.
    file: 
      dest: "/home/{{ uzer }}/.ssh/"
      mode: 0700 
      owner: "{{ user }}" 
      state: directory

  - name: Install ssh key
    copy: 
      src: "{{ source_key }}" 
      dest: "{{ dest_key }}"
      mode: 0600
      owner: "{{ user }}"

- name: create empty authorized_keys file
  file:
    path: "/home/{{ user }}/.ssh/authorized_keys"
    state: touch

- name: add pubkey to authorized_keys
  lineinfile:
    path: "/home/{{ user }}/.ssh/authorized_keys"
    line: "{{ pubkey }}"

- name: system setup | openssh | generate sshd_config file from template
  tags: openssh,ssh,system,settings
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

- name: system setup | openssh | copy issue.net
  tags: openssh,ssh,system,settings
  copy:
    src: files/openssh_issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644