
- name: Ensure .ssh directory exists.
  file: 
    dest: "/home/{{ user }}/.ssh"
    mode: 0700 
    owner: "{{ user }}" 
    state: directory

- name: Install ssh key
  copy: 
    src: "files/id_ed25519" 
    dest: "/home/{{ user }}/.ssh/id_ed25519"
    mode: 0600
    owner: "{{ user }}"

- name: Install ssh key
  copy: 
    src: "files/id_ed25519" 
    dest: "/root/.ssh/id_ed25519"
    mode: 0600
    owner: root

- name: create empty authorized_keys file
  file:
    path: "/home/{{ user }}/.ssh/authorized_keys"
    state: touch

- name: add pubkey to authorized_keys
  lineinfile:
    path: "/home/{{ user }}/.ssh/authorized_keys"
    line: "{{ pubkey }}"

- name: system setup | openssh | generate sshd_config file from template
  tags: openssh,ssh,system,settings
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

- name: system setup | openssh | copy issue.net
  tags: openssh,ssh,system,settings
  copy:
    src: files/openssh_issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644