- name: Creates directory
  file:
    path: /home/{{ user }}/Downloads
    state: directory

- name: Copy Fuchs246 repository
  get_url: 
    url: https://github.com/Fuchs246/repository.fuchs246/archive/refs/heads/main.zip
    dest: /home/{{ user }}/Downloads/repository.fuchs246-1.0.0.zip

- name: Copy Dutch IPTV repository
  get_url: 
    url: https://github.com/dut-iptv/dut-iptv.github.io/raw/master/repository.anon.iptv-latest.zip
    dest: /home/{{ user }}/Downloads/repository.anon.iptv-latest.zip
  
- name: Copy hyperion
  get_url:
    url: https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.12/Hyperion-2.0.12-Linux-armv7l.deb
    dest: /home/{{ user }}/Downloads/Hyperion-2.0.12-Linux-armv7l.deb
  when: inventory_hostname == "baldr"
