- name: Creates directory
  file:
    path: /home/{{ user }}/Backup
    state: directory
    owner: osmc
    group: osmc
    mode: 0775
    recurse: yes

- name: Stop Mediaplayer
  command: "systemctl stop mediacenter"
  become_user: "{{ user }}"

- name: Copy backup
  command: "scp -o StrictHostKeyChecking=no {{ fileserver }}:{{ backuppath }}/osmc/*.tar.gz /home/{{ user }}/Backup/"
  become_user: "{{ user }}"

- name: Get files in a folder
  find:
    paths: "/home/{{ user }}/Backup/"
  register: found_files

- name: Get latest file
  set_fact:
    latest_file: "{{ (found_files.files|sort(attribute='mtime')|last).path }}" 

- debug:
    msg: "{{ latest_file }}"

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "{{ latest_file }}"
    dest: /home/{{ user }}/.kodi/
    remote_src: yes
    owner: "{{ user }}"

- name: Start Mediaplayer
  command: "systemctl start mediacenter"
  become_user: "{{ user }}"

