- name: Creates directory
  file:
    path: /home/{{ user }}/Backup
    state: directory
    owner: osmc
    group: osmc
    mode: 0775
    recurse: yes

- name: Copy backup
  command: "scp -oStrictHostKeyChecking=no {{ fileserver }}:{{ backuppath }}*.tar.gz /home/{{ user }}/Backup/"
  become_user: "{{ user }}"

  #ansible.builtin.copy:
  #  src: bragi:/volume2/Backup/osmc/*.tar.gz
  #  dest: /home/{{ user }}/Backup/
  #  remote_src: yes

#- name: Unarchive a file that is already on the remote machine
#  ansible.builtin.unarchive:
#    src: /home/{{ user }}/Backup/
#    dest: /home/{{ user }}.kodi/
#    remote_src: yes
