- name: Creates Script directory
  file:
    path: /home/{{ user }}/Scripts
    state: directory

#- name: Copy Scripts folder
#  tags: openssh,ssh,system,settings
#  copy:
#    src: files/scripts
#    dest: /home/{{ user }}/Scripts

- debug: var=inventory_hostname

#- name: Copy Scripts
#  copy:
#    src: files/scripts{{ item }}
#    dest: /home/{{ user }}/Scripts/
#  with_items: '{{ ansible_hostname }}'