- name: Creates Script directory
  file:
    path: /home/{{ user }}/Scripts
    state: directory
    owner: osmc
    group: osmc
    mode: 0775
    recurse: yes

#- name: Copy Scripts folder
#  tags: openssh,ssh,system,settings
#  copy:
#    src: files/scripts
#    dest: /home/{{ user }}/Scripts

- debug:
    msg: "{{ hostvars[host]['varname'] }}"

- name: Copy Scripts
  copy:
    src: files/scripts/{{ item }}
    dest: /home/{{ user }}/Scripts/
  with_items: "{{ vars['scripts_' + ansible_hostname] }}"

#- name: create advancedsettings file from template
#  template:
#    src: "templates/{{ item }}.j2"
#    dest: "/etc/systemd/system/{{ item }}.service"
#    group: osmc
#    mode: 0775
#  with_items: "{{ vars['scripts_' + ansible_hostname] }}"