- name: Creates Script directory
  file:
    path: /home/{{ user }}/Scripts
    state: directory
    owner: osmc
    group: osmc
    mode: 0775
    recurse: yes

#- name: Copy Scripts folder
#  tags: openssh,ssh,system,settings
#  copy:
#    src: files/scripts
#    dest: /home/{{ user }}/Scripts

- name: Copy Scripts
  copy:
    src: files/scripts/{{ item }}
    dest: /home/{{ user }}/Scripts/
    owner: osmc
    group: osmc
    mode: 0775
  with_items: "{{ scripts }}"

- name: create service files from template
  template:
    src: "templates/services/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    owner: osmc
    group: osmc
    mode: 0644
  with_items: "{{ services }}"

- name: "enable services"
  service: 
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ services }}"