user: osmc
scripts:
  - irswitch.sh
  - shutdown.sh
  - fan_control.py

services:
  - irswitch
  - irswitch2

test1: "Deze variabele is vanuit de mediaplayer rol"

blaat: "gelukt LS087610246NL LS087610246NL"

backuppath: /volume2/Backup

services2: [
  {"name": "Fan Control", "description": "Controls the speed of the fan", "script": "fan_control.py"},
  {"name": "irswitch", "description": "Controls the speed of the fan", "script": "fan_control.py"}

]