user: osmc
scripts:
  - irswitch.sh
  - shutdown.sh
  - fan_control.py

services:
  - irswitch
  - irswitch2

test1: "Deze variabele is vanuit de mediaplayer rol"

blaat: "gelukt LS087610246NL LS087610246NL"