user: osmc
group: osmc

scriptdir: "/home/{{ user }}/Scripts/"
servicedir: "/etc/systemd/system/"

backupdir: /volume2/Backup

services: [
  {"name": "irswitch", "script": "irswitch.sh", "service": "irswitch.j2"},
  {"name": "irsshutdown", "script": "shutdown.sh", "service": "irswitch2.j2"},
  {"name": "Fan Control", "script": "fan_control.py", "service": "fan_control.j2"}
]

packages: 
  - cron
  - RPi.GPIO
  - python3-crypto
  - build-essential
  - python3-pip
  - hyperion



pip_modules:
  # - setuptools
  - wheel
  # - pycryptodomex
