---

# - name: Manage directories
#   become: true
#   ansible.builtin.file:
#     path: "/usr/share/keyrings"
#     state: directory
#     mode: "0755"

# # Fetch gpg keys for trusted apt repositories
# - name: Download apt repository gpg keys
#   become: true
#   ansible.builtin.get_url:
#     url: "https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub"
#     dest: "/usr/share/keyrings/prebuilt-mpr-archive-keyring"
#     mode: "0644"

# - name: Extract and replace gpg keys with dearmor
#   become: true
#   ansible.builtin.command:
#     cmd: "gpg --dearmor /usr/share/keyrings/prebuilt-mpr-archive-keyring"
#     creates: "/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg"

# - name: Add apt repositories
#   become: true
#   ansible.builtin.apt_repository:
#     repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr {{ ansible_distribution_release }}"

# - name: install just
#   apt:
#     name: "just"
#     state: present
#     update_cache: yes

  - name: check latest just
    uri:
      url: https://api.github.com/repos/casey/just/releases/latest
      return_content: true
    register: just_latest

  - name: "installing Just {{ just_latest.json.tag_name }}"
    unarchive:
      remote_src: yes
      src: "https://github.com/casey/just/releases/download/{{ just_latest.json.tag_name }}/just-{{ just_latest.json.tag_name }}-armv7-unknown-linux-musleabihf.tar.gz"
      dest: "/home/{{user}}/bin"


- name: generate justfile file from template
  tags: justfile
  # copy: 
  #   src: "vars/{{ ansible_host }}/files/justfile.j2" 
  #   dest: "/home/{{ user }}/.jusfile"
  template:
    src: "files/{{ ansible_host }}/templates/justfile.j2"
    dest: "/home/{{ user }}/.justfile"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644