---
  - name: install packages
    #  name: "{{ item }}"
    with_items: "{{ packages }}"
    when: packages is defined

  - name: install pip modules
    command: python3 -m pip install -U {{ item }}
    with_items: "{{ pip_modules }}"
    become: yes
    become_user: "{{ user }}"
    when: pip_modules is defined
  #- name: Installing multiple python packages in Ansible
  #  pip:
  #    name:
        #- setuptools
  #      - wheel
  #      - pycryptodomex

      #  - htop
      #  - cronie
      #  - keepass
      #  - vim
      #  - cura
      #  - code
      #  - thunderbird
      #  - nextcloud-client
      #  - libreoffice-fresh
      #  - steam
      #  - steam
      #  - wine
      #  - powerline-fonts
      #  - bc
      #  - xsel
      #  - xdotool
      #  - virtualbox
      #  - linux-headers
      #  - base-devel
      #  - dkms
