---
  - name: install packages
    package:
      name: "{{ item }}"
    with_items: "{{ packages }}"
    when: packages is defined

  - name: install pip modules
    command: python3 -m pip install -U {{ item }}
    with_items: "{{ pip_modules }}"
    become: yes
    become_user: "{{ user }}"
    when: pip_modules is defined
