---
  - name: install packages
    package:
      name: 
        - cron
        - python3-crypto
        - build-essential
        - python3-pip

  #- name: Installing multiple python packages in Ansible
  #  pip:
  #    name:
        #- setuptools
  #      - wheel
  #      - pycryptodomex

      #  - htop
      #  - cronie
      #  - keepass
      #  - vim
      #  - cura
      #  - code
      #  - thunderbird
      #  - nextcloud-client
      #  - libreoffice-fresh
      #  - steam
      #  - steam
      #  - wine
      #  - powerline-fonts
      #  - bc
      #  - xsel
      #  - xdotool
      #  - virtualbox
      #  - linux-headers
      #  - base-devel
      #  - dkms