packages: 
  - htop
  - samba
  - vim
  - cowsay
  - net-tools
  - iftop
  - nfs-common
  - mergerfs
  - nfs-kernel-server

update : sudo apt update && sudo apt upgrade -y
install : sudo apt install 

git_repos:
  - { repo: 'Ansible', url: 'https://github.com/MVrauwdeunt/Ansible' }

disks:
  - { disk: "#/dev/disk/by-id/ata-WDC_WD5000AADS-00S9B0_WD-WCAV9T179852-part1", mount: "/mnt/disk1", fs: "xfs", options: "defaults" }
  - { disk: "#/dev/disk/by-id/ata-SAMSUNG_HD103SJ_S246JD2B206681-part1", mount: "/mnt/disk2", fs: "xfs", options: "defaults" }
  - { disk: "#/dev/disk/by-id/ata-TOSHIBA_MQ01ABF050_276OCQUYT-part1", mount: "/mnt/disk3", fs: "xfs", options: "defaults" }
  - { disk: "#/dev/disk/by-id/ata-ST3500418AS_9VMTZH60-part1", mount: "/mnt/disk4", fs: "xfs", options: "defaults" }
  - { disk: "#/dev/disk/by-id/ata-ST2000DM001-1ER164_Z4Z0B28Y-part1 ", mount: "/mnt/disk5", fs: "xfs", options: "defaults" }

  - { disk: "#/dev/disk/by-id/ata-Maxtor_6L160M0_L40D9RPG-part1 ", mount: "/mnt/download1", fs: "xfs", options: "xfs defaults" }

  - { disk: "#/mnt/disk*", mount: "/volume2", fs: "fuse.mergerfs", options: "direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs" }
  - { disk: "#/mnt/download*", mount: "/volume1", fs: "fuse.mergerfs", options: "direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs" }

nfs_shares:
  - { share: "/volume2/Afbeeldingen", fsid: "1" }
  - { share: "/volume2/Documenten", fsid: "2" }
  - { share: "/volume2/Downloads", fsid: "3" }
  - { share: "/volume2/Films", fsid: "4" }
  - { share: "/volume2/Games", fsid: "5" }
  - { share: "/volume2/Muziek", fsid: "6" }
  - { share: "/volume2/Scan", fsid: "7" }
  - { share: "/volume2/Series", fsid: "8" }
  - { share: "/volume2/Slaap_Muziek", fsid: "9" }
  - { share: "/volume2/Backup", fsid: "10" }
  - { share: "/volume2/Images", fsid: "11" }

# global vars
global_env_vars:
  - "PUID=1313"
  - "PGID=1313"
appdata_path: /opt/appdata
container_config_path: /config
container_data_path: /data

# container definitions
containers:
  - service_name: letsencrypt
    active: true
    image: linuxserver/letsencrypt
    container_name: le
    ports:
      - 80:80
      - 443:443
    volumes:
      - "{{ appdata_path }}/letsencrypt/config:{{ container_config_path }}"
    restart: always
    depends_on:
      - unifi
      - nextcloud
      - quassel
    include_global_env_vars: true
    environment:
      - EMAIL=email@email.com
      - URL=some.tld
      - SUBDOMAINS=nc, irc, unifi
      - ONLY_SUBDOMAINS=true
      - DHLEVEL=4096
      - TZ=Europe/London
      - VALIDATION=http
    mem_limit: 256m


